### ISSUE TITLE
Solve the sum square difference problem.

### ISSUE THREAD

**Issue by thetaniyagupta** [hackerearthclub/CODE2RACE#1]
Solve the Sum square difference problem
https://github.com/hackerearthclub/CODE2RACE/blob/master/ASSIGNMENTS/Find%20Sum%20square%20Difference.md

**Comment by thetaniyagupta** [comment]
Yeah! sure, I'm updating the problem statement.

**Comment by thetaniyagupta** [comment]
> Hey! I would like to work on this. Can you elaborate more on the problem or give a sample test case?

Hi , i have updated the problem statement.

**Comment by fahmitok97** [comment]
Hi, I've made a solution with cplusplus, kindly review the PR. Thanks!

**Comment by iamjaspreetsingh** [comment]
Awesome @fahmitok97
