### ISSUE TITLE
Pandigital Prime

### ISSUE THREAD

**Issue by thetaniyagupta** [hackerearthclub/CODE2RACE#209]
https://github.com/hackerearthclub/CODE2RACE/blob/master/ASSIGNMENTS/Pandigital%20Prime.md

**Comment by diego95root** [comment]
Isn't the second case wrong? The input had five digits so the output should be 54321...

**Comment by thetaniyagupta** [comment]
> Isn't the second case wrong? The input had five digits so the output should be 54321...

We are finding largest n digit pan digital prime number which is less than equal to N as defined in problem statement
In this sample test case,
10000 is the input value of N.
Since pandigit number must be less than equal to N, the output for this test case has to be less than 10000, that will be a 4-digit number.

**Comment by diego95root** [comment]
Oh okay I get it now, sorry and many thanks
