### ISSUE TITLE
Solve EMPTY BOTTLES

### ISSUE THREAD

**Issue by thetaniyagupta** [hackerearthclub/CODE2RACE#235]
https://github.com/hackerearthclub/CODE2RACE/blob/master/ASSIGNMENTS/Empty%20Bottles.txt

**Comment by nfatma** [comment]
I would like to solve this.

**Comment by GinJoe** [comment]
Added solution under EmptyBottles.java in Solutions folder

**Comment by amirulabu** [comment]
completed this in python #246

**Comment by Piyush-555** [comment]
Solved in Python3 #249

**Comment by nfatma** [comment]
Solved this in C #257
