### ISSUE TITLE
Suggestion: Add some automated testing like Travis CI, Circle CI, Appveyor

### ISSUE THREAD

**Issue by cclauss** [hackerearthclub/CODE2RACE#338]
They are all free for Open Source projects like this one.

https://github.com/marketplace/category/continuous-integration

**Comment by iamjaspreetsingh** [comment]
@cclauss thanks !
will soon add the one:)

**Comment by iamjaspreetsingh** [comment]
i am closing the issue as it contains mainly questions!

**Comment by cclauss** [comment]
No questions...  Just a suggestion.  ;-)
