### ISSUE TITLE
Determine if a word is a Palindrome

### ISSUE THREAD

**Issue by dexiouz** [hackerearthclub/CODE2RACE#577]
A palindrome is a word, phrase, or sequence that reads the same backwards as forwards, e.g. madam or nurses run.
Write a function that takes in a word and returns true if the word is a palindrome. And returns false if the word is not a palindrome.
For example

let word = madam
return true, "madam is a palindrome"

let word = apple
return false, "apple is not a palindrome"

**Comment by akshayrpatel** [comment]
Can I get this assigned?
