### ISSUE TITLE
Solve ReverseDict

### ISSUE THREAD

**Issue by thetaniyagupta** [hackerearthclub/CODE2RACE#64]
https://github.com/hackerearthclub/CODE2RACE/blob/master/ASSIGNMENTS/ReverseDict

**Comment by SergiyGolov** [comment]
Hi, I would like to work on this

**Comment by SergiyGolov** [comment]
I solved it, is the code like you expected? Because it was not really clear if the ReverseDict must be reversed at his construction or only if it's printed
