### ISSUE TITLE
Solve RockPaperScissors

### ISSUE THREAD

**Issue by iamjaspreetsingh** [hackerearthclub/CODE2RACE#68]
https://github.com/hackerearthclub/CODE2RACE/blob/master/ASSIGNMENTS/rockPaperScissor.md

**Comment by RedMoon32** [comment]
#71

**Comment by RohanJnr** [comment]
Hey there ! i would like to work on making that rock paper scissor game !

**Comment by KrishnaRSampath** [comment]
Do you only want C++, or can I submit a solution in another language (e.g., Ruby, Python, JavaScript).

**Comment by iamjaspreetsingh** [comment]
@KrishnaRSampath , any language solutions are accepted !

**Comment by vodkanoya** [comment]
Hi! Can I work on the solution for this in Java?

**Comment by thetaniyagupta** [comment]
> Hi! Can I work on the solution for this in Java?

Yes you can.
