### ISSUE TITLE
solve  "Hello, World!" problem 

### ISSUE THREAD

**Issue by thetaniyagupta** [hackerearthclub/CODE2RACE#7]
Write hello world program in any language you want. Mention hello world in your file name.
https://github.com/hackerearthclub/CODE2RACE/blob/master/ASSIGNMENTS/Hello%20%20world.md

**Comment by NayakNavin** [comment]
I'll do java

**Comment by dnhuan** [comment]
#27

**Comment by prashanth9962** [comment]
Added hello world in Rust #91

**Comment by sac6120** [comment]
Added Hello world in C++
